version: '3.8'

services:
  backend:
    build: ./backend
    container_name: udrone-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    volumes:
      # Mount data directory for persistence
      - ./backend/data:/app/data
      # Mount map tiles directory
      - ./backend/map_tiles:/app/map_tiles
      # Mount logs directory
      - ./backend/logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - udrone-network

  frontend:
    build: ./frontend
    container_name: udrone-frontend
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - udrone-network

networks:
  udrone-network:
    driver: bridge
