// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/api-demo": {
    params: {};
  };
  "/data": {
    params: {};
  };
  "/ukraine-fire-tracking": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/api-demo" | "/data" | "/ukraine-fire-tracking";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/api-demo.tsx": {
    id: "routes/api-demo";
    page: "/api-demo";
  };
  "routes/data.tsx": {
    id: "routes/data";
    page: "/data";
  };
  "routes/ukraine-fire-tracking.tsx": {
    id: "routes/ukraine-fire-tracking";
    page: "/ukraine-fire-tracking";
  };
};